apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app-1-21
  template:
    metadata:
      labels:
        app: reddit-clone-app-1-21
    spec:
      containers:
        - name: reddit-clone-app-1-21
          image: zylmaimun/reddit-clone-pipeline-1.0.0-10
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
