apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-clone-app-1-34
spec:
  selector:
    app: reddit-clone-app-1-34

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
